version: "3.9"

services:
  client:
    container_name: VueJS
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  backend:
    container_name: NodeJS
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend/:/user/src/app

  database:
    container_name: MongoDB
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./db:/data/db"